### ISSUE TITLE
No songs appearing

### ISSUE THREAD

**Issue by Arthur64026** [HecticKiwi/Web-Osu-Mania#20]
I just launched the website to play a bit and no songs appears, no matter how long I wait.
![preuve](https://github.com/user-attachments/assets/94a2a050-5116-40d9-ae2c-8e0949778641)

**Comment by Aaroneljugon1** [comment]
Yeah, same. Was gonna say that

**Comment by Aaroneljugon1** [comment]
Tried changing the beatmap provider in settings. No result.

**Comment by unstablekidd** [comment]
I've had the same problem.. Hope this might be fixed sometime soon.

**Comment by HecticKiwi** [comment]
Sorry for the downtime guys, it should be fixed!

The issue was that each user on my website got their own access token on demand in order for the site to query the osu API. However, as the site grew in users, eventually the API blocked me for sending too many access token requests at once. I wasn't experienced enough to foresee this...

Now, one access token is kept in a KV store that all my backend requests share so this problem shouldn't happen anymore. Lesson learned ;)
